_locale_redirect:
     path: /
     defaults:
         _controller: FrameworkBundle:Redirect:urlRedirect
         path: /en
         permanent: true

_api:
    resource: "@JackDeckKeeperBundle/Resources/config/routing/api.yml"
    prefix: /api

_api_noroute:
    resource: "@JackDeckKeeperBundle/Resources/config/routing/noroute.yml"
    prefix: /api

_deckkeeper:
    resource: "@JackDeckKeeperBundle/Resources/config/routing/frontend.yml"
    prefix:   /{_locale}
